//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomReservation", Namespace="http://schemas.datacontract.org/2004/07/RoomReservationData")]
    public partial class RoomReservation : object
    {
        
        private string ContactField;
        
        private System.DateTime EndDateField;
        
        private string EventField;
        
        private int IdField;
        
        private string RoomNameField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact
        {
            get
            {
                return this.ContactField;
            }
            set
            {
                this.ContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Event
        {
            get
            {
                return this.EventField;
            }
            set
            {
                this.EventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomName
        {
            get
            {
                return this.RoomNameField;
            }
            set
            {
                this.RoomNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRoomService")]
    public interface IRoomService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/ReserveRoom", ReplyAction="http://tempuri.org/IRoomService/ReserveRoomResponse")]
        bool ReserveRoom(ServiceReference1.RoomReservation roomReservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/ReserveRoom", ReplyAction="http://tempuri.org/IRoomService/ReserveRoomResponse")]
        System.Threading.Tasks.Task<bool> ReserveRoomAsync(ServiceReference1.RoomReservation roomReservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetRoomReservations", ReplyAction="http://tempuri.org/IRoomService/GetRoomReservationsResponse")]
        ServiceReference1.RoomReservation[] GetRoomReservations(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetRoomReservations", ReplyAction="http://tempuri.org/IRoomService/GetRoomReservationsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.RoomReservation[]> GetRoomReservationsAsync(System.DateTime fromDate, System.DateTime toDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IRoomServiceChannel : ServiceReference1.IRoomService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class RoomServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IRoomService>, ServiceReference1.IRoomService
    {
        
        public RoomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool ReserveRoom(ServiceReference1.RoomReservation roomReservation)
        {
            return base.Channel.ReserveRoom(roomReservation);
        }
        
        public System.Threading.Tasks.Task<bool> ReserveRoomAsync(ServiceReference1.RoomReservation roomReservation)
        {
            return base.Channel.ReserveRoomAsync(roomReservation);
        }
        
        public ServiceReference1.RoomReservation[] GetRoomReservations(System.DateTime fromDate, System.DateTime toDate)
        {
            return base.Channel.GetRoomReservations(fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RoomReservation[]> GetRoomReservationsAsync(System.DateTime fromDate, System.DateTime toDate)
        {
            return base.Channel.GetRoomReservationsAsync(fromDate, toDate);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
